### ISSUE TITLE
SDK does not work on Android when using play-services-basement:15.0.0 or newer

### ISSUE THREAD

**Issue by villevli** [tenjin/tenjin-unity-sdk#26]
The SDK just fails to send any events. No errors are shown in adb logcat.
This is likely caused by some change in the Google Play Services version 15.0.0
https://developers.google.com/android/guides/releases#april_12_2018_-_version_1500

**Comment by vanner** [comment]
We have updated the Unity Package with: play-services-ads-identifier-16.0.0.aar

Google moved some classes to obtain the Advertising ID into a play-services-ads-identifier class.  I have added latest AAR file into our existing SDK.  Alternatively, you can download the file into the `/Assets/Plugins/Android/` directory: https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier
