### ISSUE TITLE
Tenjin IAP not working in arm64 unity build

### ISSUE THREAD

**Issue by babak-ss** [tenjin/tenjin-unity-sdk#32]
I had somehow the same problems with other SDK(firebase, google) that didn't have some functionalities in `x86` version but were able to solve them by force resolving Play Services Resolver. 

Purchase events seem to be working fine on other versions(`armv7` & `arm64`) see the attached photo 
[https://imgur.com/iljjCzk](https://imgur.com/iljjCzk)

**Comment by vanner** [comment]
@babak-ss - If this is still an issue, please email support@tenjin.com
