### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by Soulghai** [tenjin/tenjin-unity-sdk#33]
I have an error when I'm trying to make Android build.
Unity Said that "Build Succeeded"
But In Console I see this lines 
<img width="805" alt="Снимок экрана 2019-07-02 в 18 06 27" src="https://user-images.githubusercontent.com/710362/60519450-a1ae0380-9cf4-11e9-8098-efff0237d70c.png">
<img width="866" alt="Снимок экрана 2019-07-02 в 18 06 40" src="https://user-images.githubusercontent.com/710362/60519464-a5da2100-9cf4-11e9-880e-2ab93de2d2f0.png">

**Comment by rkachowski** [comment]
The android manifest is included in the latest `unitypackage` offered on the master branch here, I've just compiled and build a test app for android against that. I can only assume this is some kind of intermediate build failure - can you try cleaning the build / temp directory and trying again?
