### ISSUE TITLE
INSTALL_REFERRER intent is being deprecated. Does the Unity SDK implement the API?

### ISSUE THREAD

**Issue by JimmyDeemo** [tenjin/tenjin-unity-sdk#35]
The documentation for the Unity SDK talks about adding the INSTALL_REFERRER to the AndroidManifest, but this is being deprecated at the start of March; https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html.

I noticed that the Android SDK documentation talks about this; https://github.com/tenjin/tenjin-android-sdk#android-studio-integration.

Is it supported by the Unity SDK yet? Is any development works needed? What if we have multiple referrers to send the data to? Any way to check that Tenjin is receiving the right data?

**Comment by vanner** [comment]
Yes, the Unity SDK uses the latest Google Install Referrer and it is built in by default in the Unity SDK.  We only used Broadcast Referrer (INSTALL_REFERRER) as backfill in case Google Install Referrer did not return data (and Broadcast Referrer did).  

No code changes are needed if you are using the latest Unity version.  We will update the documentation and remove that section. Thank you for identifying that.

You can check if you are correctly sending Referrer Install events under the `Tenjin SDK Integration Status` section of the app details.  https://www.tenjin.io/dashboard/apps/

<img width="954" alt="Screen Shot 2020-01-10 at 10 44 53 AM" src="https://user-images.githubusercontent.com/66860/72177813-5f960680-3396-11ea-882b-e485fb45fddd.png">

**Comment by JimmyDeemo** [comment]
Thanks for the response @vanner, I have indeed checked the dashboard and can see install referrer being marked as 'received' for past versions. I will endeavor to check the the versions we prodce with the intent removed.

Just to confirm then, the SDK does this processing internally? We do not need to forward our own API integration on to the Tenjin SDK?

**Comment by JimmyDeemo** [comment]
@vanner Any thoughts on the above questions would be really helpful. Also, please can we get some ui controls for the integration status area of the dashboard? There are some very only and illigitamate builds that would be good to remove/hide.

**Comment by vanner** [comment]
@JimmyDeemo - Apologies for the delay.  For faster response in the future, please email support@tenjin.com.

Yes, the SDK will automatically handle getting the referrer and send it to our server.  For reference, the required libraries are located in `/Assets/Plugins/Android/installreferrer-*`. 

If you have any further issues, please email: support@tenjin.com
