### ISSUE TITLE
Error when fire connect() with Unity 2018.4.15f1 (64-bit) iOS editor

### ISSUE THREAD

**Issue by kaninhot004** [tenjin/tenjin-unity-sdk#36]
![IOS_Tenjin PNG](https://user-images.githubusercontent.com/9493525/80560195-3f07c000-8a0a-11ea-94dc-8334f0be34d0.png)

Work fine with Android Editor.

Anyone face this issue?

Thanks!

**Comment by vanner** [comment]
Hi @kaninhot004 - If this is still an issue, please email support@tenjin.com for support.  Thanks.
